# Generated by Django 4.2.5 on 2024-09-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='Credits',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
