# Generated by Django 4.2.5 on 2024-09-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_subjects_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll_subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=30)),
                ('Professor', models.CharField(max_length=30)),
            ],
        ),
    ]
