# Generated by Django 4.2.5 on 2024-09-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_enroll_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll_subjects',
            name='Credits',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
