# Generated by Django 4.2.5 on 2023-09-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_nondinner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cnondinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=20)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cnonlunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=20)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ctiffen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=20)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cvegdinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=20)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cveglunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=20)),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
